# Generated by Django 4.1.1 on 2022-09-09 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest', models.IntegerField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchmakingQueueModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.playermodel')),
            ],
        ),
        migrations.CreateModel(
            name='GameSessionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('session_id', models.TextField()),
                ('status', models.CharField(choices=[('ONGOING', 'ongoing'), ('FINISHED', 'finished'), ('ABORTED', 'aborted')], max_length=10)),
                ('which_player_turn', models.IntegerField()),
                ('board', models.JSONField()),
                ('black_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.playermodel')),
                ('white_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.playermodel')),
            ],
        ),
    ]
