# Generated by Django 4.1 on 2022-09-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameSessionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("white_player", models.IntegerField()),
                ("black_player", models.IntegerField()),
                ("session_id", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("ONGOING", "ongoing"), ("FINISHED", "finished")],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatchmakingQueueModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.IntegerField()),
                ("time_added", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
