# Generated by Django 4.1 on 2022-09-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameSessionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("white_player", models.IntegerField()),
                ("black_player", models.IntegerField()),
                ("session_id", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("ONGOING", "ongoing"), ("FINISHED", "finished")],
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
