# Generated by Django 4.1.1 on 2022-09-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesessionmodel",
            name="against_bot",
            field=models.BooleanField(default=False),
        ),
    ]
