# Generated by Django 4.1 on 2022-09-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesessionmodel",
            name="cos",
            field=models.IntegerField(default=1),
        ),
    ]
