# Generated by Django 4.1.1 on 2022-09-09 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="matchmakingqueuemodel",
            old_name="client_id",
            new_name="client",
        ),
    ]
