# Generated by Django 4.1.1 on 2022-09-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="matchmakingqueuemodel",
            old_name="time_added",
            new_name="last_updated",
        ),
        migrations.AddField(
            model_name="gamesessionmodel",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="gamesessionmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("ONGOING", "ongoing"),
                    ("FINISHED", "finished"),
                    ("ABORTED", "aborted"),
                ],
                max_length=10,
            ),
        ),
    ]
