# Generated by Django 4.1.1 on 2022-09-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_rename_client_id_matchmakingqueuemodel_client"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gamesessionmodel",
            old_name="white_player",
            new_name="chess_player",
        ),
        migrations.AlterField(
            model_name="gamesessionmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("ONGOING", "ongoing"),
                    ("FINISHED", "finished"),
                    ("ABORTED", "aborted"),
                    ("CHESS_WON", "chess_won"),
                    ("CHECKERS_WON", "checkers_won"),
                    ("CHESS_SURRENDERED", "chess_surrendered"),
                    ("CHECKERS_SURRENDERED", "checkers_surrendered"),
                ],
                max_length=20,
            ),
        ),
    ]
