# Generated by Django 4.1 on 2022-09-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_gamesessionmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="waitinglistmodel",
            name="time_added",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
