# Generated by Django 4.1.1 on 2022-09-08 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("game", "0002_rename_time_added_matchmakingqueuemodel_last_updated_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guest", models.IntegerField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="gamesessionmodel",
            name="black_player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="game.playermodel",
            ),
        ),
        migrations.AlterField(
            model_name="gamesessionmodel",
            name="white_player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="game.playermodel",
            ),
        ),
        migrations.AlterField(
            model_name="matchmakingqueuemodel",
            name="client_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="game.playermodel"
            ),
        ),
    ]
