# Generated by Django 4.1.1 on 2022-09-09 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_rename_white_player_gamesessionmodel_chess_player_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gamesessionmodel",
            old_name="black_player",
            new_name="checkers_player",
        ),
    ]
