# Generated by Django 4.1.1 on 2022-09-09 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_rename_black_player_gamesessionmodel_checkers_player"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gamesessionmodel",
            old_name="session_id",
            new_name="session_url",
        ),
    ]
