# Generated by Django 4.1.1 on 2022-09-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_rename_session_id_gamesessionmodel_session_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesessionmodel",
            name="checkers_player_joined",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="gamesessionmodel",
            name="chess_player_joined",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="gamesessionmodel",
            name="which_player_turn",
            field=models.IntegerField(default=0),
        ),
    ]
