# Generated by Django 4.1.1 on 2022-09-10 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0006_gamesessionmodel_checkers_player_joined_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamesessionmodel",
            name="checkers_player",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="game.playermodel",
            ),
        ),
        migrations.AlterField(
            model_name="gamesessionmodel",
            name="chess_player",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="game.playermodel",
            ),
        ),
        migrations.AlterField(
            model_name="gamesessionmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("ONGOING", "ongoing"),
                    ("ABORTED", "aborted"),
                    ("CHESS_WON", "chess_won"),
                    ("CHECKERS_WON", "checkers_won"),
                    ("CHESS_TIMEOUT", "chess_timeout"),
                    ("CHECKERS_TIMEOUT", "checkers_timeout"),
                ],
                max_length=20,
            ),
        ),
    ]
