name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{25c8b926-806e-48fd-b32d-28eebfec743e}}
          heroku_app_name: "cheskers"
          heroku_email: "leszko.lucas@gmail.com"
